sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bibek18/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bibek18/docker-react npm run test -- --coverage
